'use strict';

const ROLE_CODES = Object.freeze({
  SYS_ADMIN: 'SYS_ADMIN',
  QLCL_SPECIALIST: 'QLCL_SPECIALIST',
  REGIONAL_LEAD_APPROVER: 'REGIONAL_LEAD_APPROVER',
  DEPARTMENT_HEAD_APPROVER: 'DEPARTMENT_HEAD_APPROVER',
  BLOCK_DIRECTOR_APPROVER: 'BLOCK_DIRECTOR_APPROVER',
  SUPPLIER_USER: 'SUPPLIER_USER',
  DATA_UPLOADER: 'DATA_UPLOADER',
  AUDITOR: 'AUDITOR',
  READ_ONLY_VIEWER: 'READ_ONLY_VIEWER',
});

const PERMISSIONS = Object.freeze({
  SYSTEM_ADMIN: 'SYSTEM.ADMIN',
  USER_MANAGE: 'USER.MANAGE',
  DASHBOARD_READ: 'DASHBOARD.READ',
  AUDIT_READ: 'AUDIT.READ',
  AUDIT_EXPORT: 'AUDIT.EXPORT',
  SUPPLIER_READ: 'SUPPLIER.READ',
  SUPPLIER_WRITE: 'SUPPLIER.WRITE',
  SUPPLIER_SELF_READ: 'SUPPLIER.SELF_READ',
  EVALUATION_READ: 'EVALUATION.READ',
  EVALUATION_CREATE: 'EVALUATION.CREATE',
  EVALUATION_SCORE: 'EVALUATION.SCORE',
  EVALUATION_DELETE_DRAFT: 'EVALUATION.DELETE_DRAFT',
  EVALUATION_APPROVE_LEAD: 'EVALUATION.APPROVE_LEAD',
  EVALUATION_APPROVE_TBP: 'EVALUATION.APPROVE_TBP',
  EVALUATION_APPROVE_GDK: 'EVALUATION.APPROVE_GDK',
  REPORT_READ: 'REPORT.READ',
  REPORT_EXPORT: 'REPORT.EXPORT',
  REPORT_TEMPLATE_MANAGE: 'REPORT_TEMPLATE.MANAGE',
  REPORT_TEMPLATE_PUBLISH: 'REPORT_TEMPLATE.PUBLISH',
  REPORT_TEMPLATE_ADVANCED: 'REPORT_TEMPLATE.ADVANCED',
  QUESTION_TEMPLATE_MANAGE: 'QUESTION_TEMPLATE.MANAGE',
  SCORING_POLICY_MANAGE: 'SCORING_POLICY.MANAGE',
  SCORING_POLICY_PUBLISH: 'SCORING_POLICY.PUBLISH',
});

const ACTIVE_PERMISSION_CODES = Object.freeze(Object.values(PERMISSIONS));

function isActivePermission(permissionCode) {
  return ACTIVE_PERMISSION_CODES.includes(String(permissionCode || ''));
}

// Capabilities that grant entry to an administration surface or an
// administration-only API. Business read/export/approval permissions are
// deliberately excluded so workflow roles cannot become administrators by
// implication.
const ADMIN_PERMISSIONS = Object.freeze([
  PERMISSIONS.SYSTEM_ADMIN,
  PERMISSIONS.USER_MANAGE,
  PERMISSIONS.AUDIT_READ,
  PERMISSIONS.AUDIT_EXPORT,
  PERMISSIONS.REPORT_TEMPLATE_MANAGE,
  PERMISSIONS.REPORT_TEMPLATE_PUBLISH,
  PERMISSIONS.REPORT_TEMPLATE_ADVANCED,
  PERMISSIONS.QUESTION_TEMPLATE_MANAGE,
  PERMISSIONS.SCORING_POLICY_MANAGE,
  PERMISSIONS.SCORING_POLICY_PUBLISH,
]);

const SCOPE_TYPES = Object.freeze([
  'GLOBAL', 'REGION', 'MCH2', 'ASSIGNED', 'OWN', 'SUPPLIER', 'CUSTOM',
]);

// Compatibility input only. Authorization decisions never compare these labels.
const LEGACY_ROLE_TO_CODE = Object.freeze({
  Admin: ROLE_CODES.SYS_ADMIN,
  'Chuyên viên': ROLE_CODES.QLCL_SPECIALIST,
  'Lead miền': ROLE_CODES.REGIONAL_LEAD_APPROVER,
  TBP: ROLE_CODES.DEPARTMENT_HEAD_APPROVER,
  'GĐK': ROLE_CODES.BLOCK_DIRECTOR_APPROVER,
  NCC: ROLE_CODES.SUPPLIER_USER,
});

const ROLE_CODE_TO_LEGACY = Object.freeze(Object.fromEntries(
  Object.entries(LEGACY_ROLE_TO_CODE).map(([label, code]) => [code, label])
));

// Shared compatibility projection order. Permission decisions never depend on
// this order; it only keeps legacy identity fields deterministic.
const LEGACY_PRIMARY_ROLE_PRIORITY = Object.freeze([
  ROLE_CODES.SYS_ADMIN,
  ROLE_CODES.BLOCK_DIRECTOR_APPROVER,
  ROLE_CODES.DEPARTMENT_HEAD_APPROVER,
  ROLE_CODES.REGIONAL_LEAD_APPROVER,
  ROLE_CODES.SUPPLIER_USER,
  ROLE_CODES.QLCL_SPECIALIST,
]);

module.exports = {
  ROLE_CODES,
  PERMISSIONS,
  ACTIVE_PERMISSION_CODES,
  isActivePermission,
  ADMIN_PERMISSIONS,
  SCOPE_TYPES,
  LEGACY_ROLE_TO_CODE,
  ROLE_CODE_TO_LEGACY,
  LEGACY_PRIMARY_ROLE_PRIORITY,
};
